# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Terrence James Diaz
tagline:          'Frontend/UX/Fullstack Engineer'
description:      'Frontend/UX/Fullstack Engineer'
url:              "terrencejames.github.io"
baseurl:          "/s"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
