# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Terrence James Diaz
tagline:          'Frontend/UX/Fullstack Engineer'
description:      'Frontend/UX/Fullstack Engineer'
url:              "terrencejames.github.io"
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version:          1.0.0

github:           https://github.com/terrencejames
behance:          http://www.behance.net/terrencejames
linkedin:         https://www.linkedin.com/in/terrence-james-diaz
