# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Terrence James Diaz
tagline:          'Frontend/UX/Fullstack Engineer'
description:      'Frontend/UX/Fullstack Engineer'
url:              'terrenceja.me/'
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
